### ISSUE TITLE
about train annotation

### ISSUE THREAD

**Issue by phamhe** [KMnP/fashionpedia-api#1]
Hi Thanks for your work！
But I found there are duplicated anno id in annotations and may cause mismatch between anns and imgs when using coco api
Thanks again

**Comment by KMnP** [comment]
Thanks for spotting this issue! I have updated the file with non-duplicated annotation ids.

**Comment by phamhe** [comment]
Thank you very much
And I have been searching for annotations of modanet dataset for a while,I found that clone from modanet git repo is not usefule,becase annotations were pushed 2 years ago.
Can you share your modanet annotation with me? Thanks again!

**Comment by KMnP** [comment]
hi, we also downloaded modanet annotations from the GitHub repo, so I think what you have is the same as what I have now.

**Comment by phamhe** [comment]
hi, I do not have modanet dataset,
I download recently several times from different device and different account，and each time the same error occurred  which described as  the dataset is overdue
I think the dataset is overdue and i tried to remind author by commit issue, but nobody reply me
So could you please share dataset with me? Thank you very much!
