### ISSUE TITLE
class-agnostic attributes or not ?

### ISSUE THREAD

**Issue by xushilin1** [KMnP/fashionpedia-api#15]
Hi, 
Thanks for your excellent work and It's awesom to have segment ontology annotations.
But the attributes are class-agnostic or class-specfic?
Thanks.

**Comment by KMnP** [comment]
Hi, I assume you were talking about apparel category classes. Some of the attributes are for specific category, e.g. nickname for dresses are for dresses only. Some attributes are class-agnostic, like silhouette or textile pattern. 

I will close this issue now, pls  feel free to reopen it if you have more questions.
