### ISSUE TITLE
Wrong prediction

### ISSUE THREAD

**Issue by gireek** [KMnP/fashionpedia-api#3]
Instead of the line below in baseline_predictor_demo.ipynb
```
detections_str = '{} ({}%)'.format(ontology['categories'][detection_classes[i]]['name'],
                                           int(100*detection_scores[i]))
```
it should be this for correct class prediction:
`        detections_str = '{} ({}%)'.format(ontology['categories'][detection_classes[i]-1]['name'],int(100*detection_scores[i]))
`

And can you please open-source your training code. Lots of enthusiasts have been waiting for this code now. Thanks

**Comment by KMnP** [comment]
Thanks for catching this typo! I updated the demo accordingly. 

We are working on open-sourcing the training code now. Will make it public soon! Pls stay tuned.

**Comment by gireek** [comment]
Apologies for asking but approximately how soon can we expect it?

**Comment by KMnP** [comment]
We are planning to release it within 2 weeks :)
