### ISSUE TITLE
Model code

### ISSUE THREAD

**Issue by chaurasiat** [KMnP/fashionpedia-api#4]
Hi @KMnP when will you be open sourcing the code to build the model? Many enthusiasts are waiting for the release. Thank you

**Comment by gireek** [comment]
Hi @KMnP. It will be great if you provide the code for the architecture so beginners can work on this. Thanks

**Comment by chaurasiat** [comment]
Hi @KMnP by when can we expect the new model and checkpoints? Thank you

**Comment by richardaecn** [comment]
Hi @chaurasiat , we are waiting for final reviews of the code to be checked-in. Now we have a landing page and model ckpts / configs released at https://github.com/tensorflow/tpu/tree/master/models/official/detection/projects/fashionpedia . Other code including data conversion, model training and inference will be released soon in the next few days.

**Comment by KMnP** [comment]
The code for training is available at  [above link](https://github.com/tensorflow/tpu/tree/master/models/official/detection/projects/fashionpedia) .
