### ISSUE TITLE
Not able to restore model ckpts 

### ISSUE THREAD

**Issue by mitraavi** [KMnP/fashionpedia-api#8]
Dear Yin Cui, 

First of all it is Great! to see fashionpedia model ckpts with different backbones and their performances have been shared in: https://github.com/tensorflow/tpu/tree/master/models/official/detection/projects/fashionpedia

However, when I was trying to load a model ckpt "SpineNet-143" using following code:

with tf.Session() as sess:    
    saver = tf.train.import_meta_graph('./spinenet-143/model.ckpt.meta')
    saver.restore(sess,tf.train.latest_checkpoint('./spinenet-143/'))

 i was getting following error:

"NotFoundError: Op type not registered 'LegacyParallelInterleaveDatasetV2' in binary running on 7d386b9416f5. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed."

Could you please look into the issue and let us know as how we can load the model to test inference ?

Also it will be great if we can get frozen model (.pb format) similar to example given in "baseline_predictor_demo.ipynb" 

Thanking you!

Regards,

Abhishek

**Comment by mitraavi** [comment]
Thanks! for sharing the model training and inference codes in the tensorflow/tpu github, however, model restoration issue still persisting, here is what error I'm getting when I'm just trying to restore model from spinenet-143 ckpt:

CODE used to restore:
---------------------------------------------
saver = tf.train.Saver()
with tf.Session() as sess:    
    saver.restore(sess, './model_spinenet_143/model.ckpt')
--------------------------------------------

ERROR:
--------------------------------------------
NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

root error(s) found.
  (0) Not found: Key Variable not found in checkpoint
	 [[node save/RestoreV2 (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1748) ]]
--------------------------------------------
I'm using tensorflow-gpu 1.15.0 version in colab, any hint as this error is occurring ?
Thanks

**Comment by mitraavi** [comment]
Above error is it due to the fact that I'm trying to load a pre-trained checkpoint that was trained on TPU on GPU ?

**Comment by richardaecn** [comment]
Setting `--use_tpu=False` should work on CPU and GPU. 

For more about code release, please refer to [this link](https://github.com/KMnP/fashionpedia-api/issues/9#issuecomment-666696882)

**Comment by mitraavi** [comment]
Able to run inferences with suggestions from @richardaecn, hence closing this issue
